# Generated by Django 6.0.1 on 2026-01-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties', models.JSONField(default=list)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=255)),
                ('governing_law', models.CharField(blank=True, max_length=255)),
                ('payment_terms', models.TextField(blank=True)),
                ('termination', models.TextField(blank=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('confidentiality', models.TextField(blank=True)),
                ('indemnity', models.TextField(blank=True)),
                ('liability_cap', models.JSONField(default=dict)),
                ('signatories', models.JSONField(default=list)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.document')),
            ],
        ),
    ]
